name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Run API Tests
        run: ./gradlew apiTest

      - name: Run Web UI Tests
        run: ./gradlew webTest

      - name: Archive API Test Report
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: api-test-report
          path: build/reports/tests/apiTest

      - name: Archive Web UI Test Report
        uses: actions/upload-artifact@v4.3.0
        if: always()
        with:
          name: web-ui-test-report
          path: build/reports/tests/webTest
