name: Run API and UI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run API Tests
        run: |
          mkdir -p reports
          pytest tests/api/ --html=reports/api-report.html

      - name: Run UI Tests
        run: |
          pytest tests/ui/ --html=reports/ui-report.html

      - name: Upload API Report
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: reports/api-report.html

      - name: Upload UI Report
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-report
          path: reports/ui-report.html
