name: Web UI & API Tests with Downloadable Reports

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-html

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Web UI Tests
        run: |
          pytest tests/ui/ --html=reports/ui-report.html

      - name: Run API Tests
        run: |
          pytest tests/api/ --html=reports/api-report.html

      - name: Upload Web UI Report
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-report
          path: reports/ui-report.html

      - name: Upload API Report
        uses: actions/upload-artifact@v3
        with:
          name: api-test-report
          path: reports/api-report.html
